### ISSUE TITLE
Implement 

### ISSUE THREAD

**Issue by Tim55667757** [Tim55667757/TKSBrokerAPI#97]
`secrets.yaml` - where all account stored locally with aliases of users
`--name`, `-n`, `--alias`, `--user-name` keys for select user name and credentials from `secrets.yaml`

```yaml
Timur:
  -
    account: "accountId-1"
    comment: "Test account"
    token: "api-token-1"

  -
    account: "accountId-2"
    comment: "Main account"
    token: "api-token-2"

UserName2:
  -
    account: "accountId-3"
    comment: "Another account"
    token: "api-token"
```
